spice-labs-inc/spice-labs-cli

- grind.sh
Added in variable and calls to goatrodeo and ginger.  Iterated and did several tests of command echos and variable combinations to validate it matched expectations.  Will need to do more testing and validation once container built.
> solid draft of grind.sh file that will be ready once into container

- .github/workflows/Build_Publish.yml
- Dockerfile
> Initial dockerfile and workflow

- Dockerfile
> Adjust entry point for Dockerfile Issue #1

- grind.sh
> tweak grind.sh #1

- Dockerfile
- README.md
- grind.sh
- grinder.sh
> CLI Cleanup

- .github/workflows/Build_Publish.yml
> remove ghcr attestations

- .github/workflows/publish.yml
- README.md
- pom.xml
> update dependency versions and readme

- .gitignore
- spice
- spice-labs-cli.iml
> fix reference to potentially uninited array that makes mac bash unhappy

- README.md
- pom.xml
- src/main/java/io/spicelabs/cli/SpiceLabsCLI.java
- src/test/java/io/spicelabs/cli/SpiceLabsCLITest.java
> add --tag and --goat-rodeo-args escape hatch

- .github/workflows/promoteToLatest.yml
- .github/workflows/publish.yml
- pom.xml
> revert to isprerelease. islatest is not in the api.

- pom.xml
- spice
- spice.ps1
> fix volume mounting and add script upgrade prompt. upgrade ginger-j.

- spice
- spice.ps1
> absolutize paths properly

- .github/workflows/promoteToLatest.yml
> add write perm so that api call doesn't fail

- spice
> missed L flag for curl that makes it follow redirects

- .github/workflows/buildAndTest.yml
- .github/workflows/publish.yml
- pom.xml
- src/main/java/io/spicelabs/cli/SpiceLabsCLI.java
> move internal repos to settings.xml

- README.md
> fix local maintainer docs in readme

- README.md
Added the --tag cli option to the readme.
> add --tag cli option

- pom.xml
> upgrade goatrode to v0.10.2

- spice
> remove dep on jq

- README.md
action-spice-labs-cli-scan uses v2
> action-spice-labs-cli-scan uses v2

- .github/workflows/publish.yml
> add release notifications
